name: 'Adds a file repository in composer.json'
description: 'Adds (or replaces!) the `repositories` key in composer.json. Adds a file repo at provided relative path.'
inputs:
  repo_relative_path:
    description: 'relative path to repo'
    required: true
    default: 'packages/your/repo'    
  
runs:
  using: 'node12'
  main: 'index.js'