name: 'Merge JSON Files'
description: 'Merge one json file into another.'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
  path: # id of output
    description: 'The __dirname'    
  
runs:
  using: 'node12'
  main: 'index.js'