name: 'Merge JSON Files'
description: 'Merge one json file into another.'
inputs:
  additions:
    description: 'additions path'
    required: true
    default: 'data1.json'
  target:
    description: 'target path'
    required: true
    default: 'data2.json'    
  
runs:
  using: 'node12'
  main: 'index.js'