name: 'Merge JSON Files'
description: 'Merge one json file into another.'
inputs:
  target:
    description: 'target path'
    required: true
    default: 'data1.json'
  additions:
    description: 'serialized json to add'
    required: true
    default: '{}'    
  
runs:
  using: 'node12'
  main: 'index.js'