on: [push]

jobs:
  test_merge_job:
    runs-on: ubuntu-latest
    name: A job to test the merge
    steps:
    - name: Clone Repo
      uses: actions/checkout@v1    
    - name: Dump runner context
      env:
        runner_context: ${{ toJson(runner) }}
      run: echo "$runner_context"
    - name: Add the repo to composer.json
      uses: ajthinking/merge-json-files@master
      with:
        repo_relative_path: 'packages/Ajthinking/PHPFileManipulator'