on: [push]

jobs:
  test_merge_job:
    runs-on: ubuntu-latest
    name: A job to test the merge
    steps:
    - name: Merge two files
      id: merged
      uses: ajthinking/merge-json-files@v1.0.6
      with:
        additions: 'data1.json'
        target: 'data2.json'
