on: [push]

jobs:
  test_merge_job:
    runs-on: ubuntu-latest
    name: A job to test the merge
    steps:
    - name: Merge two files
      id: merged
      uses: ajthinking/merge-json-files@v1.0.6
      with:
        path1: 'data1.json'
        path2: 'data2.json'
    - name: ECHO output
      run: echo "The data was merged as ${{ steps.merged.outputs.data3 }}"
