on: [push]

jobs:
  test_merge_job:
    runs-on: ubuntu-latest
    name: A job to test the merge
    steps:
    - name: Add the repo to composer.json
      id: merged
      uses: ajthinking/merge-json-files@v1.0.15
      with:
        repo_relative_path: 'packages/Ajthinking/PHPFileManipulator'
